import React, { useState } from "react";
import { X, ExternalLink, Shield, Info, Calendar, User, Loader2 } from "lucide-react";
import { Asset } from "../../types";
import { motion, AnimatePresence } from "motion/react";
import { Badge } from "../ui/Badge";
import { toast } from "sonner";

interface AssetDetailsModalProps {
  asset: Asset;
  isOpen: boolean;
  onClose: () => void;
}

export default function AssetDetailsModal({ asset, isOpen, onClose }: AssetDetailsModalProps) {
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownloadReport = async () => {
    setIsDownloading(true);
    try {
      // Simulate report generation
      await new Promise(resolve => setTimeout(resolve, 1000));

      const reportContent = `
ARCHIVE IQ - ASSET CLEARANCE REPORT
Generated: ${new Date().toLocaleString()}

ASSET INFORMATION
-----------------
Name: ${asset.asset_name}
Type: ${asset.asset_type}
Source: ${asset.detected_source}
Source URL: ${asset.source_url || 'N/A'}
Last Updated: ${new Date(asset.last_updated).toLocaleString()}

CLEARANCE STATUS
----------------
Copyright Status: ${asset.copyright_status}
Risk Level: ${asset.risk_level}
Workflow Stage: ${asset.workflow_stage}
AI Confidence Score: ${(asset.ai_confidence_score * 100).toFixed(2)}%

RIGHTS HOLDER INFORMATION
-------------------------
Name: ${asset.rights_holder?.name || 'Unknown'}
Organization: ${asset.rights_holder?.organization || 'Unknown'}
Contact Email: ${asset.rights_holder?.contact_email || 'Unknown'}

DISCLAIMER
----------
This report was generated by Archive IQ AI. While we strive for accuracy, 
this does not constitute legal advice. Please consult with your legal 
department for final clearance verification.
      `.trim();

      const blob = new Blob([reportContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `clearance-report-${asset.asset_name.toLowerCase().replace(/\s+/g, '-')}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success("Report downloaded successfully");
    } catch (error) {
      toast.error("Failed to generate report");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-start justify-center p-4 overflow-y-auto bg-black/80 backdrop-blur-sm">
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 pointer-events-none"
            onClick={onClose}
          />
          
          <motion.div 
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="relative w-full max-w-5xl bg-white border border-black/5 rounded-[32px] shadow-2xl overflow-hidden my-auto flex flex-col max-h-none sm:max-h-[90vh]"
          >
            <div className="p-8 border-b border-black/5 flex justify-between items-center bg-white shrink-0">
              <div>
                <h3 className="text-2xl font-bold">Asset Details</h3>
                <p className="text-sm text-black/40">Technical metadata and clearance status</p>
              </div>
              <button onClick={onClose} className="p-3 hover:bg-black/5 rounded-full transition-colors">
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="p-8 bg-[#fcfdfe] overflow-y-auto flex-1 scrollbar-hide">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
                <div className="space-y-8">
                  <div className="aspect-video rounded-2xl overflow-hidden border border-black/5 shadow-inner bg-black/5 relative group">
                    <img 
                      src={asset.thumbnail_url} 
                      alt={asset.asset_name} 
                      className="w-full h-full object-cover"
                      referrerPolicy="no-referrer"
                    />
                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                      <ExternalLink className="w-8 h-8 text-white" />
                    </div>
                  </div>

                  <div className="space-y-4">
                    <h4 className="text-sm font-bold uppercase tracking-widest text-black/30">Clearance Status</h4>
                    <div className="p-6 bg-white border border-black/5 rounded-2xl shadow-sm space-y-4">
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-black/60">Copyright</span>
                        <Badge variant="outline" className="font-bold border-black/10">{asset.copyright_status}</Badge>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-black/60">Risk Level</span>
                        <span className={`text-sm font-bold ${asset.risk_level === 'High' ? 'text-red-500' : 'text-amber-500'}`}>
                          {asset.risk_level}
                        </span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-black/60">Workflow Stage</span>
                        <Badge className="bg-black text-white font-bold">{asset.workflow_stage}</Badge>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="space-y-8">
                  <div className="space-y-4">
                    <h4 className="text-sm font-bold uppercase tracking-widest text-black/30">Asset Metadata</h4>
                    <div className="space-y-6">
                      <div className="flex gap-4">
                        <div className="w-10 h-10 rounded-xl bg-black/5 flex items-center justify-center shrink-0">
                          <Info className="w-5 h-5 text-black/40" />
                        </div>
                        <div>
                          <p className="text-xs font-bold text-black/30 uppercase tracking-wider mb-1">Name</p>
                          <p className="text-sm font-bold text-black">{asset.asset_name}</p>
                        </div>
                      </div>

                      <div className="flex gap-4">
                        <div className="w-10 h-10 rounded-xl bg-black/5 flex items-center justify-center shrink-0">
                          <User className="w-5 h-5 text-black/40" />
                        </div>
                        <div>
                          <p className="text-xs font-bold text-black/30 uppercase tracking-wider mb-1">Source / Rights Holder</p>
                          <p className="text-sm font-bold text-black">{asset.detected_source}</p>
                        </div>
                      </div>

                      <div className="flex gap-4">
                        <div className="w-10 h-10 rounded-xl bg-black/5 flex items-center justify-center shrink-0">
                          <Calendar className="w-5 h-5 text-black/40" />
                        </div>
                        <div>
                          <p className="text-xs font-bold text-black/30 uppercase tracking-wider mb-1">Last Updated</p>
                          <p className="text-sm font-bold text-black">{new Date(asset.last_updated).toLocaleDateString()}</p>
                        </div>
                      </div>

                      <div className="flex gap-4">
                        <div className="w-10 h-10 rounded-xl bg-cyan-500/10 flex items-center justify-center shrink-0">
                          <Shield className="w-5 h-5 text-cyan-600" />
                        </div>
                        <div>
                          <p className="text-xs font-bold text-cyan-600/40 uppercase tracking-wider mb-1">AI Confidence Score</p>
                          <p className="text-sm font-bold text-cyan-600">{(asset.ai_confidence_score * 100).toFixed(1)}%</p>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className="pt-6">
                    <button 
                      onClick={handleDownloadReport}
                      disabled={isDownloading}
                      className="w-full h-12 bg-black text-white rounded-xl font-bold hover:bg-black/80 transition-colors shadow-xl shadow-black/10 flex items-center justify-center gap-2 disabled:opacity-50"
                    >
                      {isDownloading ? (
                        <>
                          <Loader2 className="w-4 h-4 animate-spin" />
                          Generating...
                        </>
                      ) : (
                        "Download Full Report"
                      )}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
